# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='type2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='position',
            new_name='type1',
        ),
    ]
