# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171209_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('subtitle', models.CharField(default='', max_length=600)),
                ('year', models.CharField(default='', max_length=300)),
                ('under', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='webmail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
