# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_team_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='', max_length=600)),
                ('year', models.CharField(default='', max_length=300)),
                ('under', models.CharField(default='', max_length=200)),
                ('created_by', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='team',
            name='under',
        ),
        migrations.RemoveField(
            model_name='team',
            name='year',
        ),
        migrations.AddField(
            model_name='details',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.team'),
        ),
    ]
