# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20171212_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='', max_length=600)),
                ('year', models.CharField(default='', max_length=300)),
                ('under', models.CharField(default='', max_length=200)),
                ('created_by', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.team'),
        ),
    ]
