# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0009_auto_20171212_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(default='', max_length=500)),
                ('team', models.CharField(default='', max_length=500)),
                ('year', models.CharField(default='', max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
