# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage1', models.CharField(default='', max_length=200)),
                ('stage2', models.CharField(default='', max_length=200)),
                ('stage3', models.CharField(default='', max_length=200)),
                ('stage4', models.CharField(default='', max_length=200)),
                ('stage5', models.CharField(default='', max_length=200)),
                ('under', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.detail')),
            ],
        ),
    ]
