# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='approved_by',
            field=models.CharField(default='', max_length=300),
        ),
    ]
