# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20171214_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='request_post',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
