# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_progress_request_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='board',
            field=models.CharField(default='', max_length=200),
        ),
    ]
