# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_profile_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='request_event',
            field=models.CharField(default='', max_length=200),
        ),
    ]
