# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_progress_request_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='under',
        ),
        migrations.AddField(
            model_name='path',
            name='Board',
            field=models.CharField(default='', max_length=200),
        ),
    ]
