# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_auto_20171214_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='type1',
            name='year',
            field=models.CharField(default=1999, max_length=200),
            preserve_default=False,
        ),
    ]
