# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_type2_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='type1',
            name='webmail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='type2',
            name='webmail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='type1',
            name='board',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='type1',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='type1',
            name='year',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='type2',
            name='board',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='type2',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='type2',
            name='year',
            field=models.CharField(default='', max_length=200),
        ),
    ]
