# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_progress_request_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='approved_by',
            new_name='currently_pending_at',
        ),
    ]
