# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_auto_20171215_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='request_at',
            new_name='request_at_state',
        ),
    ]
