# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20171215_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='created_by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
