# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_path_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='Board',
        ),
    ]
