# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_remove_path_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='under',
            field=models.CharField(default='', max_length=200),
        ),
    ]
