# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_path_under'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='currently_pending_at',
            new_name='created_by',
        ),
    ]
