# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20171216_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='request_created_by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
