# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_progress_request_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='request_at_state',
            new_name='request_at_stage',
        ),
    ]
