# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_auto_20171216_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
