# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_remove_path_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='stage4',
        ),
        migrations.RemoveField(
            model_name='path',
            name='stage5',
        ),
    ]
