# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_auto_20171219_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_progress',
            old_name='stage_0',
            new_name='stage0',
        ),
        migrations.RenameField(
            model_name='record_progress',
            old_name='stage_1',
            new_name='stage1',
        ),
        migrations.RenameField(
            model_name='record_progress',
            old_name='stage_2',
            new_name='stage2',
        ),
        migrations.RenameField(
            model_name='record_progress',
            old_name='stage_3',
            new_name='stage3',
        ),
    ]
