# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_auto_20171219_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_team_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage0', models.CharField(default='none', max_length=200)),
                ('stage1', models.CharField(default='none', max_length=200)),
                ('stage2', models.CharField(default='none', max_length=200)),
                ('stage3', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='team_approval_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_created_by', models.CharField(default='', max_length=200)),
                ('request_at_stage', models.IntegerField(default=0)),
                ('under', models.CharField(max_length=200)),
                ('pending_at', models.CharField(max_length=200)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('request_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='portal.team')),
            ],
        ),
        migrations.AlterField(
            model_name='record_progress',
            name='request_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_progress', to='portal.request_progress'),
        ),
        migrations.AddField(
            model_name='record_team_progress',
            name='request_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_approval_progress', to='portal.team_approval_progress'),
        ),
    ]
