# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_auto_20171219_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_approval_progress',
            name='team_year',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='team_approval_progress',
            name='request_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='portal.detail'),
        ),
    ]
