# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_auto_20171219_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='', max_length=200)),
                ('subtitle', models.CharField(default='', max_length=600)),
                ('year', models.CharField(default='', max_length=300)),
                ('under', models.CharField(default='', max_length=200)),
                ('created_by', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='name',
        ),
        migrations.AlterField(
            model_name='team_approval_progress',
            name='request_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='portal.team_detail'),
        ),
        migrations.DeleteModel(
            name='detail',
        ),
        migrations.DeleteModel(
            name='team',
        ),
    ]
