# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_auto_20171226_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_progress',
            name='request_event_subtitle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
