# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_auto_20180118_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_progress',
            name='rejected_by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
