# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0045_request_progress_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_approval_progress',
            name='rejection_reason',
            field=models.CharField(default='', max_length=400),
        ),
    ]
