# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_team_approval_progress_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_detail',
            name='creator_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
