# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_team_approval_progress_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_approval_progress',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team_approval_progress',
            name='logo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
