# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0050_auto_20180209_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_progress',
            name='event_color',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='request_progress',
            name='event_logo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
