# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_auto_20180212_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll_no',
            field=models.IntegerField(default='0'),
        ),
    ]
