# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0053_auto_20180212_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
