# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_profile_first_time_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
