# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0056_record_team_progress_stage4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record_team_progress',
            name='stage4',
        ),
        migrations.AddField(
            model_name='path',
            name='stage4',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
