# Generated by Django 2.0.2 on 2018-04-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0060_auto_20180318_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_progress',
            name='request_user_webmail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
