# Generated by Django 2.0.2 on 2018-04-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0061_request_progress_request_user_webmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_approval_progress',
            name='team_created_webmail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
